version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers

    steps:
      - checkout

      - restore_cache:
          key: v1-package-{{ checksum "package.json" }}

      - run: npm install
      - run: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-package-{{ checksum "package.json" }}

workflows:
  version: 2

  build:
    jobs:
      - build